/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Notes
 #	author : miyako
 #	2015/11/25
 #
 # --------------------------------------------------------------------------------*/

#include "sqlite3.h"
#include "zlib.h"
#include "zconf.h"
#include "Notes.h"

// --- Query
void Notes_GET_NOTES(sLONG_PTR *pResult, PackagePtr pParams);
void Notes_GET_ATTACHMENTS(sLONG_PTR *pResult, PackagePtr pParams);

// --- Data
void Notes_GET_DATA(sLONG_PTR *pResult, PackagePtr pParams);

// --- Notification
void Notes_SET_NOTIFICATION_METHOD(sLONG_PTR *pResult, PackagePtr pParams);
void Notes_Get_notification_method(sLONG_PTR *pResult, PackagePtr pParams);

// --- Data
void Notes_GET_PREVIEWS(sLONG_PTR *pResult, PackagePtr pParams);

// --- App
void Notes_LAUNCH(sLONG_PTR *pResult, PackagePtr pParams);
void Notes_TERMINATE(sLONG_PTR *pResult, PackagePtr pParams);

void listenerInit(void);
void listenerLoop(void);
void listenerLoopStart(void);
void listenerLoopFinish(void);
void listenerLoopExecute(void);
void listenerLoopExecuteMethod(void);

//internal variable

typedef PA_long32 process_number_t;
typedef PA_long32 process_stack_size_t;
typedef PA_long32 method_id_t;
typedef PA_Unichar* process_name_t;

void OnStartup();
void OnCloseProcess();
bool IsProcessOnExit();

bool gzipInflate(const void *ptr, int len, std::vector<uint8_t> &uncompressedBytes);