/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Notes
 #	author : miyako
 #	2017/09/13
 #
 # --------------------------------------------------------------------------------*/

#include "Notes.h"
#include "libjson.h"
#include "sqlite3.h"
#include "libjson_methods.h"

#define NOTES_APP_ID @"com.apple.Notes"

void json_set_date(JSONNODE *n, const wchar_t *name, NSDate *value, BOOL isGMT = YES);

// --- Notes
void Notes_Create_note(sLONG_PTR *pResult, PackagePtr pParams);
void Notes_GET_FOLDERS(sLONG_PTR *pResult, PackagePtr pParams);
void Notes_GET_NOTES(sLONG_PTR *pResult, PackagePtr pParams);
void Notes_GET_ATTACHMENTS(sLONG_PTR *pResult, PackagePtr pParams);
void Notes_GET_ACCOUNTS(sLONG_PTR *pResult, PackagePtr pParams);
void Notes_Create_folder(sLONG_PTR *pResult, PackagePtr pParams);
void Notes_SET_NOTIFICATION(sLONG_PTR *pResult, PackagePtr pParams);
void Notes_Get_notification(sLONG_PTR *pResult, PackagePtr pParams);
void Notes_Get_attachment(sLONG_PTR *pResult, PackagePtr pParams);
void Notes_Get_note(sLONG_PTR *pResult, PackagePtr pParams);
void Notes_Get_folder(sLONG_PTR *pResult, PackagePtr pParams);
void Notes_Get_account(sLONG_PTR *pResult, PackagePtr pParams);
