/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Notes.h
 #	source generated by 4D Plugin Wizard
 #	Project : Notes
 #	author : miyako
 #	2020/09/05
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_NOTES_H
#define PLUGIN_NOTES_H

#include "4DPluginAPI.h"
#include "4DPlugin-JSON.h"

#include "Notes.h"
#include "sqlite3.h"

#import <Carbon/Carbon.h>

#include "C_TEXT.h"
#include "ARRAY_TEXT.h"
#include "C_LONGINT.h"

#define NOTES_APP_ID @"com.apple.Notes"

#pragma mark -

void Notes_Create_note(PA_PluginParameters params);
void Notes_GET_FOLDERS(PA_PluginParameters params);
void Notes_GET_NOTES(PA_PluginParameters params);
void Notes_GET_ATTACHMENTS(PA_PluginParameters params);
void Notes_GET_ACCOUNTS(PA_PluginParameters params);
void Notes_Create_folder(PA_PluginParameters params);
void Notes_SET_NOTIFICATION(PA_PluginParameters params);
void Notes_Get_notification(PA_PluginParameters params);
void Notes_Get_attachment(PA_PluginParameters params);
void Notes_Get_note(PA_PluginParameters params);
void Notes_Get_folder(PA_PluginParameters params);
void Notes_Get_account(PA_PluginParameters params);
void Notes_SHOW(PA_PluginParameters params);

#endif /* PLUGIN_NOTES_H */
